### ISSUE TITLE
Thinning.py and  Sobel.py leads to an error: SystemError: new style getargs format but argument is not a tuple

### ISSUE THREAD

**Issue by Khaalidi** [rtshadow/biometrics#11]
`$ python gabor.py images/ppf1.png 16 --save`
calculating orientation done
smoothing angles done
computing local ridge frequency done
Traceback (most recent call last):
  File "gabor.py", line 71, in <module>
    result = gabor(im, W, angles)
  File "gabor.py", line 45, in gabor
    j * W + l)
SystemError: new style getargs format but argument is not a tuple

**And**

`$ python thining.py images/ppf1_enhanced.gif --save
`loading phase done
single thining phase done
single thining phase done
single thining phase done
single thining phase done
single thining phase done
single thining phase done
single thining phase done
thining done
Traceback (most recent call last):
  File "thining.py", line 77, in <module>
    make_thin(im)
  File "thining.py", line 59, in make_thin
    utils.load_pixels(im, loaded)
  File "/home/habib/Documents/Projects/biometrics/utils.py", line 111, in load_pixels
    im_load[i, j] = pixels[i][j]
SystemError: new style getargs format but argument is not a tuple

**Comment by Saranyamadhanagopal** [comment]
HI @Khaalidi did you resolve this issue?

**Comment by Khaalidi** [comment]
@Saranyamadhanagopal 
No, I just forgot about this issue, and I found it Python was not a good decision for this computational intentisive task, and I decided to reinvent the wheel in OpenCV C++.

If you working on some fingerprint biometric verification system, I would strongly suggest you to go for SourceAFIS, it is an open source fingerprints  verification framework, purely written in Java and have .NET port too.

**Comment by Saranyamadhanagopal** [comment]
@Khaalidi thanks for your suggestion.

**Comment by Khaalidi** [comment]
@Saranyamadhanagopal  You're Welcome
