### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by shivaprashanth27** [rtshadow/biometrics#9]
hi sir,
 I have getting these errors from your code of  crossing_number.py
 crossing_number.py [-h] image
crossing_number.py: error: too few arguments
cloud you please slove it

**Comment by jenujames7** [comment]
From Readme.md, you have to give command like 
python poincare.py images/ppf1.png 16 1 --smooth
or 
python crossing_number.py images/ppf1_enhanced_thinned.gif --save.
Giving python crossing_number.py won't help.

**Comment by shivaprashanth27** [comment]
hi sir, i just give command as you reply...but i have still errors these are following sir
please help me sir 
SyntaxError: invalid syntax
>>> crossing_number.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'crossing_number' is not defined
>>> python poincare.py images/ppf1.png 16 1 --smooth
  File "<stdin>", line 1
    python poincare.py images/ppf1.png 16 1 --smooth
                  ^
SyntaxError: invalid syntax
>>> python crossing_number.py images/ppf1_enhanced_thinned.gif --save.
  File "<stdin>", line 1
    python crossing_number.py images/ppf1_enhanced_thinned.gif --save.
                         ^
SyntaxError: invalid syntax
>>>

**Comment by shivaprashanth27** [comment]
hi sir,i was excuteted the commands what you reply.but i still have errors like the following like that...please help me sir
 
C:\Users\PRADEEP-PC\Desktop\resource\biometrics-master>python poincare.py images/ppf1.png 16 1 --smooth
Traceback (most recent call last):
  File "poincare.py", line 69, in <module>
    angles = utils.calculate_angles(im, W, f, g)
  File "C:\Users\PRADEEP-PC\Desktop\resource\biometrics-master\utils.py", line 39, in calculate_angles
    Gx = apply_kernel_at(get_pixel, xSobel, k, l)
  File "C:\Users\PRADEEP-PC\Desktop\resource\biometrics-master\utils.py", line 10, in apply_kernel_at
    kernel_size = len(kernel)
TypeError: object of type 'map' has no len()

C:\Users\PRADEEP-PC\Desktop\resource\biometrics-master>python crossing_number.py images/ppf1_enhanced_thinned.gif --save.
usage: crossing_number.py [-h] image
crossing_number.py: error: unrecognized arguments: --save.

C:\Users\PRADEEP-PC\Desktop\resource\biometrics-master>
